### ISSUE TITLE
Memory leak error

### ISSUE THREAD

**Issue by gevro** [Griffan/VerifyBamID#34]
Hi,
I am getting this warning repeatedly when running VerifyBamID:
[bam_plp_destroy] memory leak: 6. Continue anyway.

I read online this may be due to unsorted BAM. However, this is still occurring after running samtools sort.

**Comment by Griffan** [comment]
Could you please provide more information, for example, htslib version, system information and bam file status? It would be ideal to provide a small dataset that can reproduce this problem.

**Comment by gevro** [comment]
1.14 (using htslib 1.14)
samtools quickcheck on the file is fine

NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux"

Can you send me an e-mail address to send you the test file directly? I replicated with a BAM file with 500k alignments. Interestingly, the first 100k alignments don't cause the problem. There is some threshold minimum # of alignments that triggers this.

**Comment by Griffan** [comment]
@gevro griffanzhang2013@gmail.com

**Comment by Griffan** [comment]
@gevro Hi, I have tested your dataset and I cannot reproduce your issue. But since this is related to the htslib API, and your samtools worked fine(I would suggest to use samtools to generate pileup files), maybe you can check if you are linked to the same htslib binary files? 

However, I did search your case and found out that this is a known issue in htslib which has been fixed. https://github.com/samtools/htslib/issues/299 
There is also a discussion about this memory leak on Biostars. https://www.biostars.org/p/173354/

**Comment by gevro** [comment]
How do I check which htslib version VerifyBamID is linked to? VerifyBamID 2.0.1 was installed by our computing admin.

**Comment by gevro** [comment]
Reinstalled with newer htslib link, and that fixed the problem.
